export type Tvsc =
  | 'abyss'
  | 'dark_vs'
  | 'light_vs'
  | 'hc_black'
  | 'dark_plus'
  | 'light_plus'
  | 'kimbie_dark'
  | 'monokai'
  | 'monokai_dimmed'
  | 'quietlight'
  | 'red'
  | 'solarized_dark'
  | 'solarized_light'

export type Tmaterial =
  | 'Darker-High-Contrast'
  | 'Darker'
  | 'Default-High-Contrast'
  | 'Default'
  | 'Lighter-High-Contrast'
  | 'Lighter'
  | 'Ocean-High-Contrast'
  | 'Ocean'
  | 'Palenight-High-Contrast'
  | 'Palenight'

export type Tnice =
  | 'nord'
  | 'min-light'
  | 'min-dark'
  | 'white'
  | 'white-night'
  | 'zeit'