// Generated by packages/langs/scripts/prepare.ts
import type { DynamicImportLanguageRegistration, BundledLanguageInfo } from '@shikijs/types'

export const bundledLanguagesInfo: BundledLanguageInfo[] = [
  {
    'id': 'abap',
    'name': 'ABAP',
    'import': (() => import('@shikijs/langs/abap')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'actionscript-3',
    'name': 'ActionScript',
    'import': (() => import('@shikijs/langs/actionscript-3')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'ada',
    'name': 'Ada',
    'import': (() => import('@shikijs/langs/ada')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'angular-html',
    'name': 'Angular HTML',
    'import': (() => import('@shikijs/langs/angular-html')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'angular-ts',
    'name': 'Angular TypeScript',
    'import': (() => import('@shikijs/langs/angular-ts')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'apache',
    'name': 'Apache Conf',
    'import': (() => import('@shikijs/langs/apache')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'apex',
    'name': 'Apex',
    'import': (() => import('@shikijs/langs/apex')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'apl',
    'name': 'APL',
    'import': (() => import('@shikijs/langs/apl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'applescript',
    'name': 'AppleScript',
    'import': (() => import('@shikijs/langs/applescript')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'ara',
    'name': 'Ara',
    'import': (() => import('@shikijs/langs/ara')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'asciidoc',
    'name': 'AsciiDoc',
    'aliases': [
      'adoc'
    ],
    'import': (() => import('@shikijs/langs/asciidoc')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'asm',
    'name': 'Assembly',
    'import': (() => import('@shikijs/langs/asm')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'astro',
    'name': 'Astro',
    'import': (() => import('@shikijs/langs/astro')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'awk',
    'name': 'AWK',
    'import': (() => import('@shikijs/langs/awk')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'ballerina',
    'name': 'Ballerina',
    'import': (() => import('@shikijs/langs/ballerina')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'bat',
    'name': 'Batch File',
    'aliases': [
      'batch'
    ],
    'import': (() => import('@shikijs/langs/bat')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'beancount',
    'name': 'Beancount',
    'import': (() => import('@shikijs/langs/beancount')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'berry',
    'name': 'Berry',
    'aliases': [
      'be'
    ],
    'import': (() => import('@shikijs/langs/berry')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'bibtex',
    'name': 'BibTeX',
    'import': (() => import('@shikijs/langs/bibtex')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'bicep',
    'name': 'Bicep',
    'import': (() => import('@shikijs/langs/bicep')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'blade',
    'name': 'Blade',
    'import': (() => import('@shikijs/langs/blade')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'bsl',
    'name': '1C (Enterprise)',
    'aliases': [
      '1c'
    ],
    'import': (() => import('@shikijs/langs/bsl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'c',
    'name': 'C',
    'import': (() => import('@shikijs/langs/c')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'cadence',
    'name': 'Cadence',
    'aliases': [
      'cdc'
    ],
    'import': (() => import('@shikijs/langs/cadence')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'cairo',
    'name': 'Cairo',
    'import': (() => import('@shikijs/langs/cairo')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'clarity',
    'name': 'Clarity',
    'import': (() => import('@shikijs/langs/clarity')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'clojure',
    'name': 'Clojure',
    'aliases': [
      'clj'
    ],
    'import': (() => import('@shikijs/langs/clojure')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'cmake',
    'name': 'CMake',
    'import': (() => import('@shikijs/langs/cmake')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'cobol',
    'name': 'COBOL',
    'import': (() => import('@shikijs/langs/cobol')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'codeowners',
    'name': 'CODEOWNERS',
    'import': (() => import('@shikijs/langs/codeowners')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'codeql',
    'name': 'CodeQL',
    'aliases': [
      'ql'
    ],
    'import': (() => import('@shikijs/langs/codeql')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'coffee',
    'name': 'CoffeeScript',
    'aliases': [
      'coffeescript'
    ],
    'import': (() => import('@shikijs/langs/coffee')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'common-lisp',
    'name': 'Common Lisp',
    'aliases': [
      'lisp'
    ],
    'import': (() => import('@shikijs/langs/common-lisp')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'coq',
    'name': 'Coq',
    'import': (() => import('@shikijs/langs/coq')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'cpp',
    'name': 'C++',
    'aliases': [
      'c++'
    ],
    'import': (() => import('@shikijs/langs/cpp')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'crystal',
    'name': 'Crystal',
    'import': (() => import('@shikijs/langs/crystal')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'csharp',
    'name': 'C#',
    'aliases': [
      'c#',
      'cs'
    ],
    'import': (() => import('@shikijs/langs/csharp')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'css',
    'name': 'CSS',
    'import': (() => import('@shikijs/langs/css')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'csv',
    'name': 'CSV',
    'import': (() => import('@shikijs/langs/csv')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'cue',
    'name': 'CUE',
    'import': (() => import('@shikijs/langs/cue')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'cypher',
    'name': 'Cypher',
    'aliases': [
      'cql'
    ],
    'import': (() => import('@shikijs/langs/cypher')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'd',
    'name': 'D',
    'import': (() => import('@shikijs/langs/d')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'dart',
    'name': 'Dart',
    'import': (() => import('@shikijs/langs/dart')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'dax',
    'name': 'DAX',
    'import': (() => import('@shikijs/langs/dax')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'desktop',
    'name': 'Desktop',
    'import': (() => import('@shikijs/langs/desktop')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'diff',
    'name': 'Diff',
    'import': (() => import('@shikijs/langs/diff')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'docker',
    'name': 'Dockerfile',
    'aliases': [
      'dockerfile'
    ],
    'import': (() => import('@shikijs/langs/docker')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'dotenv',
    'name': 'dotEnv',
    'import': (() => import('@shikijs/langs/dotenv')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'dream-maker',
    'name': 'Dream Maker',
    'import': (() => import('@shikijs/langs/dream-maker')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'edge',
    'name': 'Edge',
    'import': (() => import('@shikijs/langs/edge')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'elixir',
    'name': 'Elixir',
    'import': (() => import('@shikijs/langs/elixir')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'elm',
    'name': 'Elm',
    'import': (() => import('@shikijs/langs/elm')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'emacs-lisp',
    'name': 'Emacs Lisp',
    'aliases': [
      'elisp'
    ],
    'import': (() => import('@shikijs/langs/emacs-lisp')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'erb',
    'name': 'ERB',
    'import': (() => import('@shikijs/langs/erb')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'erlang',
    'name': 'Erlang',
    'aliases': [
      'erl'
    ],
    'import': (() => import('@shikijs/langs/erlang')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'fennel',
    'name': 'Fennel',
    'import': (() => import('@shikijs/langs/fennel')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'fish',
    'name': 'Fish',
    'import': (() => import('@shikijs/langs/fish')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'fluent',
    'name': 'Fluent',
    'aliases': [
      'ftl'
    ],
    'import': (() => import('@shikijs/langs/fluent')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'fortran-fixed-form',
    'name': 'Fortran (Fixed Form)',
    'aliases': [
      'f',
      'for',
      'f77'
    ],
    'import': (() => import('@shikijs/langs/fortran-fixed-form')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'fortran-free-form',
    'name': 'Fortran (Free Form)',
    'aliases': [
      'f90',
      'f95',
      'f03',
      'f08',
      'f18'
    ],
    'import': (() => import('@shikijs/langs/fortran-free-form')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'fsharp',
    'name': 'F#',
    'aliases': [
      'f#',
      'fs'
    ],
    'import': (() => import('@shikijs/langs/fsharp')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'gdresource',
    'name': 'GDResource',
    'import': (() => import('@shikijs/langs/gdresource')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'gdscript',
    'name': 'GDScript',
    'import': (() => import('@shikijs/langs/gdscript')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'gdshader',
    'name': 'GDShader',
    'import': (() => import('@shikijs/langs/gdshader')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'genie',
    'name': 'Genie',
    'import': (() => import('@shikijs/langs/genie')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'gherkin',
    'name': 'Gherkin',
    'import': (() => import('@shikijs/langs/gherkin')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'git-commit',
    'name': 'Git Commit Message',
    'import': (() => import('@shikijs/langs/git-commit')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'git-rebase',
    'name': 'Git Rebase Message',
    'import': (() => import('@shikijs/langs/git-rebase')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'gleam',
    'name': 'Gleam',
    'import': (() => import('@shikijs/langs/gleam')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'glimmer-js',
    'name': 'Glimmer JS',
    'aliases': [
      'gjs'
    ],
    'import': (() => import('@shikijs/langs/glimmer-js')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'glimmer-ts',
    'name': 'Glimmer TS',
    'aliases': [
      'gts'
    ],
    'import': (() => import('@shikijs/langs/glimmer-ts')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'glsl',
    'name': 'GLSL',
    'import': (() => import('@shikijs/langs/glsl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'gnuplot',
    'name': 'Gnuplot',
    'import': (() => import('@shikijs/langs/gnuplot')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'go',
    'name': 'Go',
    'import': (() => import('@shikijs/langs/go')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'graphql',
    'name': 'GraphQL',
    'aliases': [
      'gql'
    ],
    'import': (() => import('@shikijs/langs/graphql')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'groovy',
    'name': 'Groovy',
    'import': (() => import('@shikijs/langs/groovy')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'hack',
    'name': 'Hack',
    'import': (() => import('@shikijs/langs/hack')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'haml',
    'name': 'Ruby Haml',
    'import': (() => import('@shikijs/langs/haml')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'handlebars',
    'name': 'Handlebars',
    'aliases': [
      'hbs'
    ],
    'import': (() => import('@shikijs/langs/handlebars')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'haskell',
    'name': 'Haskell',
    'aliases': [
      'hs'
    ],
    'import': (() => import('@shikijs/langs/haskell')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'haxe',
    'name': 'Haxe',
    'import': (() => import('@shikijs/langs/haxe')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'hcl',
    'name': 'HashiCorp HCL',
    'import': (() => import('@shikijs/langs/hcl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'hjson',
    'name': 'Hjson',
    'import': (() => import('@shikijs/langs/hjson')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'hlsl',
    'name': 'HLSL',
    'import': (() => import('@shikijs/langs/hlsl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'html',
    'name': 'HTML',
    'import': (() => import('@shikijs/langs/html')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'html-derivative',
    'name': 'HTML (Derivative)',
    'import': (() => import('@shikijs/langs/html-derivative')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'http',
    'name': 'HTTP',
    'import': (() => import('@shikijs/langs/http')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'hurl',
    'name': 'Hurl',
    'import': (() => import('@shikijs/langs/hurl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'hxml',
    'name': 'HXML',
    'import': (() => import('@shikijs/langs/hxml')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'hy',
    'name': 'Hy',
    'import': (() => import('@shikijs/langs/hy')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'imba',
    'name': 'Imba',
    'import': (() => import('@shikijs/langs/imba')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'ini',
    'name': 'INI',
    'aliases': [
      'properties'
    ],
    'import': (() => import('@shikijs/langs/ini')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'java',
    'name': 'Java',
    'import': (() => import('@shikijs/langs/java')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'javascript',
    'name': 'JavaScript',
    'aliases': [
      'js',
      'cjs',
      'mjs'
    ],
    'import': (() => import('@shikijs/langs/javascript')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'jinja',
    'name': 'Jinja',
    'import': (() => import('@shikijs/langs/jinja')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'jison',
    'name': 'Jison',
    'import': (() => import('@shikijs/langs/jison')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'json',
    'name': 'JSON',
    'import': (() => import('@shikijs/langs/json')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'json5',
    'name': 'JSON5',
    'import': (() => import('@shikijs/langs/json5')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'jsonc',
    'name': 'JSON with Comments',
    'import': (() => import('@shikijs/langs/jsonc')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'jsonl',
    'name': 'JSON Lines',
    'import': (() => import('@shikijs/langs/jsonl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'jsonnet',
    'name': 'Jsonnet',
    'import': (() => import('@shikijs/langs/jsonnet')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'jssm',
    'name': 'JSSM',
    'aliases': [
      'fsl'
    ],
    'import': (() => import('@shikijs/langs/jssm')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'jsx',
    'name': 'JSX',
    'import': (() => import('@shikijs/langs/jsx')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'julia',
    'name': 'Julia',
    'aliases': [
      'jl'
    ],
    'import': (() => import('@shikijs/langs/julia')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'kdl',
    'name': 'KDL',
    'import': (() => import('@shikijs/langs/kdl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'kotlin',
    'name': 'Kotlin',
    'aliases': [
      'kt',
      'kts'
    ],
    'import': (() => import('@shikijs/langs/kotlin')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'kusto',
    'name': 'Kusto',
    'aliases': [
      'kql'
    ],
    'import': (() => import('@shikijs/langs/kusto')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'latex',
    'name': 'LaTeX',
    'import': (() => import('@shikijs/langs/latex')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'lean',
    'name': 'Lean 4',
    'aliases': [
      'lean4'
    ],
    'import': (() => import('@shikijs/langs/lean')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'less',
    'name': 'Less',
    'import': (() => import('@shikijs/langs/less')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'liquid',
    'name': 'Liquid',
    'import': (() => import('@shikijs/langs/liquid')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'llvm',
    'name': 'LLVM IR',
    'import': (() => import('@shikijs/langs/llvm')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'log',
    'name': 'Log file',
    'import': (() => import('@shikijs/langs/log')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'logo',
    'name': 'Logo',
    'import': (() => import('@shikijs/langs/logo')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'lua',
    'name': 'Lua',
    'import': (() => import('@shikijs/langs/lua')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'luau',
    'name': 'Luau',
    'import': (() => import('@shikijs/langs/luau')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'make',
    'name': 'Makefile',
    'aliases': [
      'makefile'
    ],
    'import': (() => import('@shikijs/langs/make')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'markdown',
    'name': 'Markdown',
    'aliases': [
      'md'
    ],
    'import': (() => import('@shikijs/langs/markdown')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'marko',
    'name': 'Marko',
    'import': (() => import('@shikijs/langs/marko')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'matlab',
    'name': 'MATLAB',
    'import': (() => import('@shikijs/langs/matlab')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'mdc',
    'name': 'MDC',
    'import': (() => import('@shikijs/langs/mdc')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'mdx',
    'name': 'MDX',
    'import': (() => import('@shikijs/langs/mdx')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'mermaid',
    'name': 'Mermaid',
    'aliases': [
      'mmd'
    ],
    'import': (() => import('@shikijs/langs/mermaid')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'mipsasm',
    'name': 'MIPS Assembly',
    'aliases': [
      'mips'
    ],
    'import': (() => import('@shikijs/langs/mipsasm')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'mojo',
    'name': 'Mojo',
    'import': (() => import('@shikijs/langs/mojo')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'move',
    'name': 'Move',
    'import': (() => import('@shikijs/langs/move')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'narrat',
    'name': 'Narrat Language',
    'aliases': [
      'nar'
    ],
    'import': (() => import('@shikijs/langs/narrat')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'nextflow',
    'name': 'Nextflow',
    'aliases': [
      'nf'
    ],
    'import': (() => import('@shikijs/langs/nextflow')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'nginx',
    'name': 'Nginx',
    'import': (() => import('@shikijs/langs/nginx')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'nim',
    'name': 'Nim',
    'import': (() => import('@shikijs/langs/nim')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'nix',
    'name': 'Nix',
    'import': (() => import('@shikijs/langs/nix')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'nushell',
    'name': 'nushell',
    'aliases': [
      'nu'
    ],
    'import': (() => import('@shikijs/langs/nushell')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'objective-c',
    'name': 'Objective-C',
    'aliases': [
      'objc'
    ],
    'import': (() => import('@shikijs/langs/objective-c')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'objective-cpp',
    'name': 'Objective-C++',
    'import': (() => import('@shikijs/langs/objective-cpp')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'ocaml',
    'name': 'OCaml',
    'import': (() => import('@shikijs/langs/ocaml')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'pascal',
    'name': 'Pascal',
    'import': (() => import('@shikijs/langs/pascal')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'perl',
    'name': 'Perl',
    'import': (() => import('@shikijs/langs/perl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'php',
    'name': 'PHP',
    'import': (() => import('@shikijs/langs/php')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'pkl',
    'name': 'Pkl',
    'import': (() => import('@shikijs/langs/pkl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'plsql',
    'name': 'PL/SQL',
    'import': (() => import('@shikijs/langs/plsql')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'po',
    'name': 'Gettext PO',
    'aliases': [
      'pot',
      'potx'
    ],
    'import': (() => import('@shikijs/langs/po')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'polar',
    'name': 'Polar',
    'import': (() => import('@shikijs/langs/polar')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'postcss',
    'name': 'PostCSS',
    'import': (() => import('@shikijs/langs/postcss')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'powerquery',
    'name': 'PowerQuery',
    'import': (() => import('@shikijs/langs/powerquery')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'powershell',
    'name': 'PowerShell',
    'aliases': [
      'ps',
      'ps1'
    ],
    'import': (() => import('@shikijs/langs/powershell')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'prisma',
    'name': 'Prisma',
    'import': (() => import('@shikijs/langs/prisma')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'prolog',
    'name': 'Prolog',
    'import': (() => import('@shikijs/langs/prolog')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'proto',
    'name': 'Protocol Buffer 3',
    'aliases': [
      'protobuf'
    ],
    'import': (() => import('@shikijs/langs/proto')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'pug',
    'name': 'Pug',
    'aliases': [
      'jade'
    ],
    'import': (() => import('@shikijs/langs/pug')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'puppet',
    'name': 'Puppet',
    'import': (() => import('@shikijs/langs/puppet')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'purescript',
    'name': 'PureScript',
    'import': (() => import('@shikijs/langs/purescript')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'python',
    'name': 'Python',
    'aliases': [
      'py'
    ],
    'import': (() => import('@shikijs/langs/python')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'qml',
    'name': 'QML',
    'import': (() => import('@shikijs/langs/qml')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'qmldir',
    'name': 'QML Directory',
    'import': (() => import('@shikijs/langs/qmldir')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'qss',
    'name': 'Qt Style Sheets',
    'import': (() => import('@shikijs/langs/qss')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'r',
    'name': 'R',
    'import': (() => import('@shikijs/langs/r')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'racket',
    'name': 'Racket',
    'import': (() => import('@shikijs/langs/racket')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'raku',
    'name': 'Raku',
    'aliases': [
      'perl6'
    ],
    'import': (() => import('@shikijs/langs/raku')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'razor',
    'name': 'ASP.NET Razor',
    'import': (() => import('@shikijs/langs/razor')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'reg',
    'name': 'Windows Registry Script',
    'import': (() => import('@shikijs/langs/reg')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'regexp',
    'name': 'RegExp',
    'aliases': [
      'regex'
    ],
    'import': (() => import('@shikijs/langs/regexp')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'rel',
    'name': 'Rel',
    'import': (() => import('@shikijs/langs/rel')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'riscv',
    'name': 'RISC-V',
    'import': (() => import('@shikijs/langs/riscv')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'rosmsg',
    'name': 'ROS Interface',
    'import': (() => import('@shikijs/langs/rosmsg')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'rst',
    'name': 'reStructuredText',
    'import': (() => import('@shikijs/langs/rst')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'ruby',
    'name': 'Ruby',
    'aliases': [
      'rb'
    ],
    'import': (() => import('@shikijs/langs/ruby')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'rust',
    'name': 'Rust',
    'aliases': [
      'rs'
    ],
    'import': (() => import('@shikijs/langs/rust')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'sas',
    'name': 'SAS',
    'import': (() => import('@shikijs/langs/sas')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'sass',
    'name': 'Sass',
    'import': (() => import('@shikijs/langs/sass')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'scala',
    'name': 'Scala',
    'import': (() => import('@shikijs/langs/scala')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'scheme',
    'name': 'Scheme',
    'import': (() => import('@shikijs/langs/scheme')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'scss',
    'name': 'SCSS',
    'import': (() => import('@shikijs/langs/scss')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'sdbl',
    'name': '1C (Query)',
    'aliases': [
      '1c-query'
    ],
    'import': (() => import('@shikijs/langs/sdbl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'shaderlab',
    'name': 'ShaderLab',
    'aliases': [
      'shader'
    ],
    'import': (() => import('@shikijs/langs/shaderlab')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'shellscript',
    'name': 'Shell',
    'aliases': [
      'bash',
      'sh',
      'shell',
      'zsh'
    ],
    'import': (() => import('@shikijs/langs/shellscript')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'shellsession',
    'name': 'Shell Session',
    'aliases': [
      'console'
    ],
    'import': (() => import('@shikijs/langs/shellsession')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'smalltalk',
    'name': 'Smalltalk',
    'import': (() => import('@shikijs/langs/smalltalk')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'solidity',
    'name': 'Solidity',
    'import': (() => import('@shikijs/langs/solidity')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'soy',
    'name': 'Closure Templates',
    'aliases': [
      'closure-templates'
    ],
    'import': (() => import('@shikijs/langs/soy')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'sparql',
    'name': 'SPARQL',
    'import': (() => import('@shikijs/langs/sparql')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'splunk',
    'name': 'Splunk Query Language',
    'aliases': [
      'spl'
    ],
    'import': (() => import('@shikijs/langs/splunk')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'sql',
    'name': 'SQL',
    'import': (() => import('@shikijs/langs/sql')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'ssh-config',
    'name': 'SSH Config',
    'import': (() => import('@shikijs/langs/ssh-config')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'stata',
    'name': 'Stata',
    'import': (() => import('@shikijs/langs/stata')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'stylus',
    'name': 'Stylus',
    'aliases': [
      'styl'
    ],
    'import': (() => import('@shikijs/langs/stylus')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'svelte',
    'name': 'Svelte',
    'import': (() => import('@shikijs/langs/svelte')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'swift',
    'name': 'Swift',
    'import': (() => import('@shikijs/langs/swift')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'system-verilog',
    'name': 'SystemVerilog',
    'import': (() => import('@shikijs/langs/system-verilog')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'systemd',
    'name': 'Systemd Units',
    'import': (() => import('@shikijs/langs/systemd')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'talonscript',
    'name': 'TalonScript',
    'aliases': [
      'talon'
    ],
    'import': (() => import('@shikijs/langs/talonscript')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'tasl',
    'name': 'Tasl',
    'import': (() => import('@shikijs/langs/tasl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'tcl',
    'name': 'Tcl',
    'import': (() => import('@shikijs/langs/tcl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'templ',
    'name': 'Templ',
    'import': (() => import('@shikijs/langs/templ')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'terraform',
    'name': 'Terraform',
    'aliases': [
      'tf',
      'tfvars'
    ],
    'import': (() => import('@shikijs/langs/terraform')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'tex',
    'name': 'TeX',
    'import': (() => import('@shikijs/langs/tex')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'toml',
    'name': 'TOML',
    'import': (() => import('@shikijs/langs/toml')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'ts-tags',
    'name': 'TypeScript with Tags',
    'aliases': [
      'lit'
    ],
    'import': (() => import('@shikijs/langs/ts-tags')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'tsv',
    'name': 'TSV',
    'import': (() => import('@shikijs/langs/tsv')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'tsx',
    'name': 'TSX',
    'import': (() => import('@shikijs/langs/tsx')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'turtle',
    'name': 'Turtle',
    'import': (() => import('@shikijs/langs/turtle')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'twig',
    'name': 'Twig',
    'import': (() => import('@shikijs/langs/twig')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'typescript',
    'name': 'TypeScript',
    'aliases': [
      'ts',
      'cts',
      'mts'
    ],
    'import': (() => import('@shikijs/langs/typescript')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'typespec',
    'name': 'TypeSpec',
    'aliases': [
      'tsp'
    ],
    'import': (() => import('@shikijs/langs/typespec')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'typst',
    'name': 'Typst',
    'aliases': [
      'typ'
    ],
    'import': (() => import('@shikijs/langs/typst')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'v',
    'name': 'V',
    'import': (() => import('@shikijs/langs/v')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'vala',
    'name': 'Vala',
    'import': (() => import('@shikijs/langs/vala')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'vb',
    'name': 'Visual Basic',
    'aliases': [
      'cmd'
    ],
    'import': (() => import('@shikijs/langs/vb')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'verilog',
    'name': 'Verilog',
    'import': (() => import('@shikijs/langs/verilog')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'vhdl',
    'name': 'VHDL',
    'import': (() => import('@shikijs/langs/vhdl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'viml',
    'name': 'Vim Script',
    'aliases': [
      'vim',
      'vimscript'
    ],
    'import': (() => import('@shikijs/langs/viml')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'vue',
    'name': 'Vue',
    'import': (() => import('@shikijs/langs/vue')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'vue-html',
    'name': 'Vue HTML',
    'import': (() => import('@shikijs/langs/vue-html')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'vue-vine',
    'name': 'Vue Vine',
    'import': (() => import('@shikijs/langs/vue-vine')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'vyper',
    'name': 'Vyper',
    'aliases': [
      'vy'
    ],
    'import': (() => import('@shikijs/langs/vyper')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'wasm',
    'name': 'WebAssembly',
    'import': (() => import('@shikijs/langs/wasm')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'wenyan',
    'name': 'Wenyan',
    'aliases': [
      '文言'
    ],
    'import': (() => import('@shikijs/langs/wenyan')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'wgsl',
    'name': 'WGSL',
    'import': (() => import('@shikijs/langs/wgsl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'wikitext',
    'name': 'Wikitext',
    'aliases': [
      'mediawiki',
      'wiki'
    ],
    'import': (() => import('@shikijs/langs/wikitext')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'wit',
    'name': 'WebAssembly Interface Types',
    'import': (() => import('@shikijs/langs/wit')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'wolfram',
    'name': 'Wolfram',
    'aliases': [
      'wl'
    ],
    'import': (() => import('@shikijs/langs/wolfram')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'xml',
    'name': 'XML',
    'import': (() => import('@shikijs/langs/xml')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'xsl',
    'name': 'XSL',
    'import': (() => import('@shikijs/langs/xsl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'yaml',
    'name': 'YAML',
    'aliases': [
      'yml'
    ],
    'import': (() => import('@shikijs/langs/yaml')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'zenscript',
    'name': 'ZenScript',
    'import': (() => import('@shikijs/langs/zenscript')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'zig',
    'name': 'Zig',
    'import': (() => import('@shikijs/langs/zig')) as DynamicImportLanguageRegistration
  }
]

export const bundledLanguagesBase = Object.fromEntries(bundledLanguagesInfo.map(i => [i.id, i.import]))

export const bundledLanguagesAlias = Object.fromEntries(bundledLanguagesInfo.flatMap(i => i.aliases?.map(a => [a, i.import]) || []))

export type BundledLanguage =
  | '1c'
  | '1c-query'
  | 'abap'
  | 'actionscript-3'
  | 'ada'
  | 'adoc'
  | 'angular-html'
  | 'angular-ts'
  | 'apache'
  | 'apex'
  | 'apl'
  | 'applescript'
  | 'ara'
  | 'asciidoc'
  | 'asm'
  | 'astro'
  | 'awk'
  | 'ballerina'
  | 'bash'
  | 'bat'
  | 'batch'
  | 'be'
  | 'beancount'
  | 'berry'
  | 'bibtex'
  | 'bicep'
  | 'blade'
  | 'bsl'
  | 'c'
  | 'c#'
  | 'c++'
  | 'cadence'
  | 'cairo'
  | 'cdc'
  | 'cjs'
  | 'clarity'
  | 'clj'
  | 'clojure'
  | 'closure-templates'
  | 'cmake'
  | 'cmd'
  | 'cobol'
  | 'codeowners'
  | 'codeql'
  | 'coffee'
  | 'coffeescript'
  | 'common-lisp'
  | 'console'
  | 'coq'
  | 'cpp'
  | 'cql'
  | 'crystal'
  | 'cs'
  | 'csharp'
  | 'css'
  | 'csv'
  | 'cts'
  | 'cue'
  | 'cypher'
  | 'd'
  | 'dart'
  | 'dax'
  | 'desktop'
  | 'diff'
  | 'docker'
  | 'dockerfile'
  | 'dotenv'
  | 'dream-maker'
  | 'edge'
  | 'elisp'
  | 'elixir'
  | 'elm'
  | 'emacs-lisp'
  | 'erb'
  | 'erl'
  | 'erlang'
  | 'f'
  | 'f#'
  | 'f03'
  | 'f08'
  | 'f18'
  | 'f77'
  | 'f90'
  | 'f95'
  | 'fennel'
  | 'fish'
  | 'fluent'
  | 'for'
  | 'fortran-fixed-form'
  | 'fortran-free-form'
  | 'fs'
  | 'fsharp'
  | 'fsl'
  | 'ftl'
  | 'gdresource'
  | 'gdscript'
  | 'gdshader'
  | 'genie'
  | 'gherkin'
  | 'git-commit'
  | 'git-rebase'
  | 'gjs'
  | 'gleam'
  | 'glimmer-js'
  | 'glimmer-ts'
  | 'glsl'
  | 'gnuplot'
  | 'go'
  | 'gql'
  | 'graphql'
  | 'groovy'
  | 'gts'
  | 'hack'
  | 'haml'
  | 'handlebars'
  | 'haskell'
  | 'haxe'
  | 'hbs'
  | 'hcl'
  | 'hjson'
  | 'hlsl'
  | 'hs'
  | 'html'
  | 'html-derivative'
  | 'http'
  | 'hurl'
  | 'hxml'
  | 'hy'
  | 'imba'
  | 'ini'
  | 'jade'
  | 'java'
  | 'javascript'
  | 'jinja'
  | 'jison'
  | 'jl'
  | 'js'
  | 'json'
  | 'json5'
  | 'jsonc'
  | 'jsonl'
  | 'jsonnet'
  | 'jssm'
  | 'jsx'
  | 'julia'
  | 'kdl'
  | 'kotlin'
  | 'kql'
  | 'kt'
  | 'kts'
  | 'kusto'
  | 'latex'
  | 'lean'
  | 'lean4'
  | 'less'
  | 'liquid'
  | 'lisp'
  | 'lit'
  | 'llvm'
  | 'log'
  | 'logo'
  | 'lua'
  | 'luau'
  | 'make'
  | 'makefile'
  | 'markdown'
  | 'marko'
  | 'matlab'
  | 'md'
  | 'mdc'
  | 'mdx'
  | 'mediawiki'
  | 'mermaid'
  | 'mips'
  | 'mipsasm'
  | 'mjs'
  | 'mmd'
  | 'mojo'
  | 'move'
  | 'mts'
  | 'nar'
  | 'narrat'
  | 'nextflow'
  | 'nf'
  | 'nginx'
  | 'nim'
  | 'nix'
  | 'nu'
  | 'nushell'
  | 'objc'
  | 'objective-c'
  | 'objective-cpp'
  | 'ocaml'
  | 'pascal'
  | 'perl'
  | 'perl6'
  | 'php'
  | 'pkl'
  | 'plsql'
  | 'po'
  | 'polar'
  | 'postcss'
  | 'pot'
  | 'potx'
  | 'powerquery'
  | 'powershell'
  | 'prisma'
  | 'prolog'
  | 'properties'
  | 'proto'
  | 'protobuf'
  | 'ps'
  | 'ps1'
  | 'pug'
  | 'puppet'
  | 'purescript'
  | 'py'
  | 'python'
  | 'ql'
  | 'qml'
  | 'qmldir'
  | 'qss'
  | 'r'
  | 'racket'
  | 'raku'
  | 'razor'
  | 'rb'
  | 'reg'
  | 'regex'
  | 'regexp'
  | 'rel'
  | 'riscv'
  | 'rosmsg'
  | 'rs'
  | 'rst'
  | 'ruby'
  | 'rust'
  | 'sas'
  | 'sass'
  | 'scala'
  | 'scheme'
  | 'scss'
  | 'sdbl'
  | 'sh'
  | 'shader'
  | 'shaderlab'
  | 'shell'
  | 'shellscript'
  | 'shellsession'
  | 'smalltalk'
  | 'solidity'
  | 'soy'
  | 'sparql'
  | 'spl'
  | 'splunk'
  | 'sql'
  | 'ssh-config'
  | 'stata'
  | 'styl'
  | 'stylus'
  | 'svelte'
  | 'swift'
  | 'system-verilog'
  | 'systemd'
  | 'talon'
  | 'talonscript'
  | 'tasl'
  | 'tcl'
  | 'templ'
  | 'terraform'
  | 'tex'
  | 'tf'
  | 'tfvars'
  | 'toml'
  | 'ts'
  | 'ts-tags'
  | 'tsp'
  | 'tsv'
  | 'tsx'
  | 'turtle'
  | 'twig'
  | 'typ'
  | 'typescript'
  | 'typespec'
  | 'typst'
  | 'v'
  | 'vala'
  | 'vb'
  | 'verilog'
  | 'vhdl'
  | 'vim'
  | 'viml'
  | 'vimscript'
  | 'vue'
  | 'vue-html'
  | 'vue-vine'
  | 'vy'
  | 'vyper'
  | 'wasm'
  | 'wenyan'
  | 'wgsl'
  | 'wiki'
  | 'wikitext'
  | 'wit'
  | 'wl'
  | 'wolfram'
  | 'xml'
  | 'xsl'
  | 'yaml'
  | 'yml'
  | 'zenscript'
  | 'zig'
  | 'zsh'
  | '文言'

export const bundledLanguages = {
  ...bundledLanguagesBase,
  ...bundledLanguagesAlias,
} as Record<BundledLanguage, DynamicImportLanguageRegistration>
