// Generated by packages/themes/scripts/prepare.ts
import type { DynamicImportThemeRegistration, BundledThemeInfo } from '@shikijs/core'

export const bundledThemesInfo: BundledThemeInfo[] = [
  {
    "id": "andromeeda",
    "displayName": "Andromeeda",
    "type": "dark",
    "import": (() => import('@shikijs/themes/andromeeda')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "aurora-x",
    "displayName": "Aurora X",
    "type": "dark",
    "import": (() => import('@shikijs/themes/aurora-x')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "ayu-dark",
    "displayName": "Ayu Dark",
    "type": "dark",
    "import": (() => import('@shikijs/themes/ayu-dark')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "catppuccin-frappe",
    "displayName": "Catppuccin Frappé",
    "type": "dark",
    "import": (() => import('@shikijs/themes/catppuccin-frappe')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "catppuccin-latte",
    "displayName": "Catppuccin Latte",
    "type": "light",
    "import": (() => import('@shikijs/themes/catppuccin-latte')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "catppuccin-macchiato",
    "displayName": "Catppuccin Macchiato",
    "type": "dark",
    "import": (() => import('@shikijs/themes/catppuccin-macchiato')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "catppuccin-mocha",
    "displayName": "Catppuccin Mocha",
    "type": "dark",
    "import": (() => import('@shikijs/themes/catppuccin-mocha')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "dark-plus",
    "displayName": "Dark Plus",
    "type": "dark",
    "import": (() => import('@shikijs/themes/dark-plus')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "dracula",
    "displayName": "Dracula Theme",
    "type": "dark",
    "import": (() => import('@shikijs/themes/dracula')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "dracula-soft",
    "displayName": "Dracula Theme Soft",
    "type": "dark",
    "import": (() => import('@shikijs/themes/dracula-soft')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "everforest-dark",
    "displayName": "Everforest Dark",
    "type": "dark",
    "import": (() => import('@shikijs/themes/everforest-dark')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "everforest-light",
    "displayName": "Everforest Light",
    "type": "light",
    "import": (() => import('@shikijs/themes/everforest-light')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "github-dark",
    "displayName": "GitHub Dark",
    "type": "dark",
    "import": (() => import('@shikijs/themes/github-dark')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "github-dark-default",
    "displayName": "GitHub Dark Default",
    "type": "dark",
    "import": (() => import('@shikijs/themes/github-dark-default')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "github-dark-dimmed",
    "displayName": "GitHub Dark Dimmed",
    "type": "dark",
    "import": (() => import('@shikijs/themes/github-dark-dimmed')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "github-dark-high-contrast",
    "displayName": "GitHub Dark High Contrast",
    "type": "dark",
    "import": (() => import('@shikijs/themes/github-dark-high-contrast')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "github-light",
    "displayName": "GitHub Light",
    "type": "light",
    "import": (() => import('@shikijs/themes/github-light')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "github-light-default",
    "displayName": "GitHub Light Default",
    "type": "light",
    "import": (() => import('@shikijs/themes/github-light-default')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "github-light-high-contrast",
    "displayName": "GitHub Light High Contrast",
    "type": "light",
    "import": (() => import('@shikijs/themes/github-light-high-contrast')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "gruvbox-dark-hard",
    "displayName": "Gruvbox Dark Hard",
    "type": "dark",
    "import": (() => import('@shikijs/themes/gruvbox-dark-hard')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "gruvbox-dark-medium",
    "displayName": "Gruvbox Dark Medium",
    "type": "dark",
    "import": (() => import('@shikijs/themes/gruvbox-dark-medium')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "gruvbox-dark-soft",
    "displayName": "Gruvbox Dark Soft",
    "type": "dark",
    "import": (() => import('@shikijs/themes/gruvbox-dark-soft')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "gruvbox-light-hard",
    "displayName": "Gruvbox Light Hard",
    "type": "light",
    "import": (() => import('@shikijs/themes/gruvbox-light-hard')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "gruvbox-light-medium",
    "displayName": "Gruvbox Light Medium",
    "type": "light",
    "import": (() => import('@shikijs/themes/gruvbox-light-medium')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "gruvbox-light-soft",
    "displayName": "Gruvbox Light Soft",
    "type": "light",
    "import": (() => import('@shikijs/themes/gruvbox-light-soft')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "houston",
    "displayName": "Houston",
    "type": "dark",
    "import": (() => import('@shikijs/themes/houston')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "kanagawa-dragon",
    "displayName": "Kanagawa Dragon",
    "type": "dark",
    "import": (() => import('@shikijs/themes/kanagawa-dragon')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "kanagawa-lotus",
    "displayName": "Kanagawa Lotus",
    "type": "light",
    "import": (() => import('@shikijs/themes/kanagawa-lotus')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "kanagawa-wave",
    "displayName": "Kanagawa Wave",
    "type": "dark",
    "import": (() => import('@shikijs/themes/kanagawa-wave')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "laserwave",
    "displayName": "LaserWave",
    "type": "dark",
    "import": (() => import('@shikijs/themes/laserwave')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "light-plus",
    "displayName": "Light Plus",
    "type": "light",
    "import": (() => import('@shikijs/themes/light-plus')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "material-theme",
    "displayName": "Material Theme",
    "type": "dark",
    "import": (() => import('@shikijs/themes/material-theme')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "material-theme-darker",
    "displayName": "Material Theme Darker",
    "type": "dark",
    "import": (() => import('@shikijs/themes/material-theme-darker')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "material-theme-lighter",
    "displayName": "Material Theme Lighter",
    "type": "light",
    "import": (() => import('@shikijs/themes/material-theme-lighter')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "material-theme-ocean",
    "displayName": "Material Theme Ocean",
    "type": "dark",
    "import": (() => import('@shikijs/themes/material-theme-ocean')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "material-theme-palenight",
    "displayName": "Material Theme Palenight",
    "type": "dark",
    "import": (() => import('@shikijs/themes/material-theme-palenight')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "min-dark",
    "displayName": "Min Dark",
    "type": "dark",
    "import": (() => import('@shikijs/themes/min-dark')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "min-light",
    "displayName": "Min Light",
    "type": "light",
    "import": (() => import('@shikijs/themes/min-light')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "monokai",
    "displayName": "Monokai",
    "type": "dark",
    "import": (() => import('@shikijs/themes/monokai')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "night-owl",
    "displayName": "Night Owl",
    "type": "dark",
    "import": (() => import('@shikijs/themes/night-owl')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "nord",
    "displayName": "Nord",
    "type": "dark",
    "import": (() => import('@shikijs/themes/nord')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "one-dark-pro",
    "displayName": "One Dark Pro",
    "type": "dark",
    "import": (() => import('@shikijs/themes/one-dark-pro')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "one-light",
    "displayName": "One Light",
    "type": "light",
    "import": (() => import('@shikijs/themes/one-light')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "plastic",
    "displayName": "Plastic",
    "type": "dark",
    "import": (() => import('@shikijs/themes/plastic')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "poimandres",
    "displayName": "Poimandres",
    "type": "dark",
    "import": (() => import('@shikijs/themes/poimandres')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "red",
    "displayName": "Red",
    "type": "dark",
    "import": (() => import('@shikijs/themes/red')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "rose-pine",
    "displayName": "Rosé Pine",
    "type": "dark",
    "import": (() => import('@shikijs/themes/rose-pine')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "rose-pine-dawn",
    "displayName": "Rosé Pine Dawn",
    "type": "light",
    "import": (() => import('@shikijs/themes/rose-pine-dawn')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "rose-pine-moon",
    "displayName": "Rosé Pine Moon",
    "type": "dark",
    "import": (() => import('@shikijs/themes/rose-pine-moon')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "slack-dark",
    "displayName": "Slack Dark",
    "type": "dark",
    "import": (() => import('@shikijs/themes/slack-dark')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "slack-ochin",
    "displayName": "Slack Ochin",
    "type": "light",
    "import": (() => import('@shikijs/themes/slack-ochin')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "snazzy-light",
    "displayName": "Snazzy Light",
    "type": "light",
    "import": (() => import('@shikijs/themes/snazzy-light')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "solarized-dark",
    "displayName": "Solarized Dark",
    "type": "dark",
    "import": (() => import('@shikijs/themes/solarized-dark')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "solarized-light",
    "displayName": "Solarized Light",
    "type": "light",
    "import": (() => import('@shikijs/themes/solarized-light')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "synthwave-84",
    "displayName": "Synthwave '84",
    "type": "dark",
    "import": (() => import('@shikijs/themes/synthwave-84')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "tokyo-night",
    "displayName": "Tokyo Night",
    "type": "dark",
    "import": (() => import('@shikijs/themes/tokyo-night')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "vesper",
    "displayName": "Vesper",
    "type": "dark",
    "import": (() => import('@shikijs/themes/vesper')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "vitesse-black",
    "displayName": "Vitesse Black",
    "type": "dark",
    "import": (() => import('@shikijs/themes/vitesse-black')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "vitesse-dark",
    "displayName": "Vitesse Dark",
    "type": "dark",
    "import": (() => import('@shikijs/themes/vitesse-dark')) as unknown as DynamicImportThemeRegistration
  },
  {
    "id": "vitesse-light",
    "displayName": "Vitesse Light",
    "type": "light",
    "import": (() => import('@shikijs/themes/vitesse-light')) as unknown as DynamicImportThemeRegistration
  }
]

export type BundledTheme =
  | 'andromeeda'
  | 'aurora-x'
  | 'ayu-dark'
  | 'catppuccin-frappe'
  | 'catppuccin-latte'
  | 'catppuccin-macchiato'
  | 'catppuccin-mocha'
  | 'dark-plus'
  | 'dracula'
  | 'dracula-soft'
  | 'everforest-dark'
  | 'everforest-light'
  | 'github-dark'
  | 'github-dark-default'
  | 'github-dark-dimmed'
  | 'github-dark-high-contrast'
  | 'github-light'
  | 'github-light-default'
  | 'github-light-high-contrast'
  | 'gruvbox-dark-hard'
  | 'gruvbox-dark-medium'
  | 'gruvbox-dark-soft'
  | 'gruvbox-light-hard'
  | 'gruvbox-light-medium'
  | 'gruvbox-light-soft'
  | 'houston'
  | 'kanagawa-dragon'
  | 'kanagawa-lotus'
  | 'kanagawa-wave'
  | 'laserwave'
  | 'light-plus'
  | 'material-theme'
  | 'material-theme-darker'
  | 'material-theme-lighter'
  | 'material-theme-ocean'
  | 'material-theme-palenight'
  | 'min-dark'
  | 'min-light'
  | 'monokai'
  | 'night-owl'
  | 'nord'
  | 'one-dark-pro'
  | 'one-light'
  | 'plastic'
  | 'poimandres'
  | 'red'
  | 'rose-pine'
  | 'rose-pine-dawn'
  | 'rose-pine-moon'
  | 'slack-dark'
  | 'slack-ochin'
  | 'snazzy-light'
  | 'solarized-dark'
  | 'solarized-light'
  | 'synthwave-84'
  | 'tokyo-night'
  | 'vesper'
  | 'vitesse-black'
  | 'vitesse-dark'
  | 'vitesse-light'

export const bundledThemes = Object.fromEntries(bundledThemesInfo.map(i => [i.id, i.import])) as Record<BundledTheme, DynamicImportThemeRegistration>
