packages:
  - packages/*
  - packages/*/playground
  - playground
  - examples/*
  - docs
  - packages/@shikijs/core/vendor/*
catalog:
  '@antfu/eslint-config': ^3.4.1
  '@antfu/ni': ^0.23.0
  '@antfu/utils': ^0.7.10
  '@iconify-json/carbon': ^1.2.1
  '@iconify-json/codicon': ^1.2.0
  '@iconify-json/ph': ^1.2.0
  '@iconify-json/svg-spinners': ^1.2.0
  '@rollup/plugin-alias': ^5.1.0
  '@rollup/plugin-commonjs': ^26.0.1
  '@rollup/plugin-json': ^6.1.0
  '@rollup/plugin-node-resolve': ^15.2.3
  '@rollup/plugin-replace': ^5.0.7
  '@rollup/plugin-terser': ^0.4.4
  '@shikijs/vscode-textmate': ^9.2.2
  '@types/fs-extra': ^11.0.4
  '@types/hast': ^3.0.4
  '@types/markdown-it': ^14.1.2
  '@types/minimist': ^1.2.5
  '@types/node': ^22.5.4
  '@unocss/reset': ^0.62.3
  '@vitest/coverage-v8': ^2.0.5
  '@vueuse/core': ^11.0.3
  ansi-sequence-parser: ^1.1.1
  bumpp: ^9.5.2
  chalk: ^5.3.0
  eslint: ^9.10.0
  eslint-plugin-format: ^0.1.2
  esno: ^4.7.0
  fast-glob: ^3.3.2
  floating-vue: ^5.2.2
  fs-extra: ^11.2.0
  fuse.js: ^7.0.0
  hast-util-from-html: ^2.0.2
  hast-util-to-html: ^9.0.2
  hast-util-to-string: ^3.0.0
  jiti: ^1.21.6
  jsonc-parser: ^3.3.1
  lint-staged: ^15.2.10
  markdown-it: ^14.1.0
  mdast-util-from-markdown: ^2.0.1
  mdast-util-gfm: ^3.0.0
  mdast-util-to-hast: ^13.2.0
  minimist: ^1.2.8
  monaco-editor-core: ^0.51.0
  ofetch: ^1.3.4
  oniguruma-to-js: 0.3.3
  picocolors: ^1.1.0
  pinia: ^2.2.2
  pnpm: ^9.10.0
  prettier: ^3.3.3
  regex: 4.3.2
  rehype-raw: ^7.0.0
  rehype-stringify: ^10.0.0
  remark-parse: ^11.0.0
  remark-rehype: ^11.1.0
  rimraf: ^6.0.1
  rollup: ^4.21.2
  rollup-plugin-copy: ^3.5.0
  rollup-plugin-dts: ^6.1.1
  rollup-plugin-esbuild: ^6.1.1
  rollup-plugin-typescript2: ^0.36.0
  shiki-legacy: npm:shiki@^0.14.7
  simple-git-hooks: ^2.11.1
  taze: ^0.16.7
  tm-grammars: ^1.17.18
  tm-themes: ^1.8.1
  twoslash: ^0.2.11
  twoslash-vue: ^0.2.11
  typescript: ^5.5.4
  unbuild: ^2.0.0
  unified: ^11.0.5
  unist-util-visit: ^5.0.0
  unocss: ^0.62.3
  unplugin-vue-components: ^0.27.4
  vite: ^5.4.3
  vite-tsconfig-paths: ^5.0.1
  vitepress: ^1.3.4
  vitepress-plugin-mermaid: ^2.0.16
  vitest: ^2.0.5
  vscode-oniguruma: ^1.7.0
  vue: ^3.5.3
  vue-tsc: ^2.1.6
  wrangler: ^3.75.0
