packages:
  - packages/*
  - packages/*/playground
  - playground
  - examples/*
  - docs
catalogs:
  bundling:
    '@rollup/plugin-alias': ^5.1.1
    '@rollup/plugin-commonjs': ^28.0.6
    '@rollup/plugin-json': ^6.1.0
    '@rollup/plugin-node-resolve': ^16.0.1
    '@rollup/plugin-replace': ^6.0.2
    '@rollup/plugin-terser': ^0.4.4
    esbuild: ^0.25.6
    rollup: ^4.45.1
    rollup-plugin-copy: ^3.5.0
    rollup-plugin-dts: ^6.2.1
    rollup-plugin-esbuild: ^6.2.1
    unbuild: ^3.5.0
    vite: ^7.0.5
    vite-tsconfig-paths: ^5.1.4
  cli:
    '@antfu/eslint-config': ^4.17.0
    '@antfu/ni': ^25.0.0
    bumpp: ^10.2.0
    eslint: ^9.31.0
    eslint-plugin-format: ^1.0.1
    jiti: ^2.4.2
    lint-staged: ^16.1.2
    pinia: ^3.0.3
    pnpm: ^10.13.1
    prettier: ^3.6.2
    rimraf: ^6.0.1
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    tsx: ^4.20.3
    typescript: ^5.8.3
    vue-tsc: ^3.0.2
    wrangler: ^4.25.0
  docs:
    '@unocss/reset': ^66.3.3
    '@vueuse/core': ^13.5.0
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    unocss: ^66.3.3
    unplugin-vue-components: ^28.8.0
    vitepress: ^2.0.0-alpha.8
    vitepress-plugin-group-icons: ^1.6.1
    vitepress-plugin-mermaid: ^2.0.17
    vue: ^3.5.17
  icons:
    '@iconify-json/carbon': ^1.2.10
    '@iconify-json/codicon': ^1.2.24
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/svg-spinners': ^1.2.2
  inlined:
    ansi-sequence-parser: ^1.1.3
    hast-util-from-html: ^2.0.3
    hast-util-to-html: ^9.0.5
    hast-util-to-string: ^3.0.1
    tm-grammars: ^1.24.0
    tm-themes: ^1.10.7
    vscode-oniguruma: 1.7.0
  integrations:
    markdown-it: ^14.1.0
    markdown-it-async: ^2.2.0
    mdast-util-from-markdown: ^2.0.2
    mdast-util-gfm: ^3.1.0
    mdast-util-to-hast: ^13.2.0
    monaco-editor-core: ^0.52.2
    rehype-raw: ^7.0.0
    rehype-stringify: ^10.0.1
    remark-parse: ^11.0.0
    remark-rehype: ^11.1.2
    twoslash: ^0.3.2
    twoslash-vue: ^0.3.2
    unified: ^11.0.5
    unist-util-visit: ^5.0.0
  prod:
    '@shikijs/vscode-textmate': ^10.0.2
    ansis: ^4.1.0
    cac: ^6.7.14
    oniguruma-to-es: ^4.3.3
  testing:
    '@vitest/coverage-v8': ^3.2.4
    diff-match-patch-es: ^1.0.1
    fast-glob: ^3.3.3
    fs-extra: ^11.3.0
    js-yaml: ^4.1.0
    ohash: ^2.0.11
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
  types:
    '@types/fs-extra': ^11.0.4
    '@types/hast': ^3.0.4
    '@types/js-yaml': ^4.0.9
    '@types/markdown-it': ^14.1.2
    '@types/mdast': ^4.0.4
    '@types/node': ^24.0.14
    '@types/unist': ^3.0.3
onlyBuiltDependencies:
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - workerd
