catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - packages/*
  - packages/*/playground
  - playground
  - examples/*
  - docs
catalogs:
  bundling:
    '@rollup/plugin-alias': ^6.0.0
    '@rollup/plugin-commonjs': ^29.0.0
    '@rollup/plugin-json': ^6.1.0
    '@rollup/plugin-node-resolve': ^16.0.3
    '@rollup/plugin-replace': ^6.0.3
    '@rollup/plugin-terser': ^0.4.4
    esbuild: ^0.27.2
    rollup: ^4.55.1
    rollup-plugin-copy: ^3.5.0
    rollup-plugin-dts: ^6.3.0
    rollup-plugin-esbuild: ^6.2.1
    unbuild: ^3.6.1
    vite: ^7.3.1
    vite-tsconfig-paths: ^6.0.3
  cli:
    '@antfu/eslint-config': ^6.7.3
    '@antfu/ni': ^28.1.0
    bumpp: ^10.3.2
    eslint: ^9.39.2
    eslint-plugin-format: ^1.2.0
    jiti: ^2.6.1
    lint-staged: ^16.2.7
    pinia: ^3.0.4
    pnpm: ^10.27.0
    prettier: ^3.7.4
    rimraf: ^6.1.2
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    tsx: ^4.21.0
    typescript: ^5.9.3
    vue-tsc: ^3.2.2
    wrangler: ^4.54.0
  docs:
    '@unocss/reset': ^66.5.12
    '@vueuse/core': ^14.1.0
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    unocss: ^66.5.12
    unplugin-vue-components: ^30.0.0
    vitepress: ^2.0.0-alpha.15
    vitepress-plugin-group-icons: ^1.6.5
    vitepress-plugin-mermaid: ^2.0.17
    vue: ^3.5.26
  icons:
    '@iconify-json/carbon': ^1.2.15
    '@iconify-json/codicon': ^1.2.39
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/svg-spinners': ^1.2.4
  inlined:
    ansi-sequence-parser: ^1.1.3
    hast-util-from-html: ^2.0.3
    hast-util-to-html: ^9.0.5
    hast-util-to-string: ^3.0.1
    tm-grammars: ^1.27.0
    tm-themes: ^1.10.14
    vscode-oniguruma: 1.7.0
  integrations:
    lz-string: ^1.5.0
    magic-string: ^0.30.21
    markdown-it: ^14.1.0
    markdown-it-async: ^2.2.0
    mdast-util-from-markdown: ^2.0.2
    mdast-util-gfm: ^3.1.0
    mdast-util-to-hast: ^13.2.1
    monaco-editor-core: ^0.55.1
    ohash: ^2.0.11
    rehype-raw: ^7.0.0
    rehype-stringify: ^10.0.1
    remark-parse: ^11.0.0
    remark-rehype: ^11.1.2
    twoslash: ^0.3.6
    twoslash-vue: ^0.3.6
    unified: ^11.0.5
    unist-util-visit: ^5.0.0
  prod:
    '@shikijs/vscode-textmate': ^10.0.2
    ansis: ^4.2.0
    cac: ^6.7.14
    oniguruma-to-es: ^4.3.4
  testing:
    '@vitest/coverage-v8': ^3.2.4
    diff-match-patch-es: ^1.0.1
    fast-glob: ^3.3.3
    fs-extra: ^11.3.3
    js-yaml: ^4.1.1
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
  types:
    '@types/fs-extra': ^11.0.4
    '@types/hast': ^3.0.4
    '@types/js-yaml': ^4.0.9
    '@types/markdown-it': ^14.1.2
    '@types/mdast': ^4.0.4
    '@types/node': ^24.10.4
    '@types/unist': ^3.0.3
onlyBuiltDependencies:
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - workerd
