packages:
  - packages/*
  - packages/*/playground
  - playground
  - examples/*
  - docs
  - packages/@shikijs/core/vendor/*
catalog:
  '@antfu/eslint-config': ^4.4.0
  '@antfu/ni': ^23.3.1
  '@antfu/utils': ^9.1.0
  '@iconify-json/carbon': ^1.2.8
  '@iconify-json/codicon': ^1.2.12
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/svg-spinners': ^1.2.2
  '@rollup/plugin-alias': ^5.1.1
  '@rollup/plugin-commonjs': ^28.0.2
  '@rollup/plugin-json': ^6.1.0
  '@rollup/plugin-node-resolve': ^16.0.0
  '@rollup/plugin-replace': ^6.0.2
  '@rollup/plugin-terser': ^0.4.4
  '@shikijs/vscode-textmate': ^10.0.2
  '@types/fs-extra': ^11.0.4
  '@types/hast': ^3.0.4
  '@types/js-yaml': ^4.0.9
  '@types/markdown-it': ^14.1.2
  '@types/mdast': ^4.0.4
  '@types/minimist': ^1.2.5
  '@types/node': ^22.13.8
  '@types/unist': ^3.0.3
  '@unocss/reset': ^66.0.0
  '@vitest/coverage-v8': ^3.0.7
  '@vueuse/core': ^12.7.0
  ansi-sequence-parser: ^1.1.3
  ansis: ^3.17.0
  bumpp: ^10.0.3
  cac: ^6.7.14
  diff-match-patch-es: ^1.0.1
  eslint: ^9.21.0
  eslint-plugin-format: ^1.0.1
  esno: ^4.8.0
  fast-glob: ^3.3.3
  find-up-simple: ^1.0.0
  floating-vue: ^5.2.2
  fs-extra: ^11.3.0
  fuse.js: ^7.1.0
  hast-util-from-html: ^2.0.3
  hast-util-to-html: ^9.0.5
  hast-util-to-string: ^3.0.1
  jiti: ^2.4.2
  js-yaml: ^4.1.0
  jsonc-parser: ^3.3.1
  lint-staged: ^15.4.3
  markdown-it: ^14.1.0
  markdown-it-async: ^2.0.0
  mdast-util-from-markdown: ^2.0.2
  mdast-util-gfm: ^3.1.0
  mdast-util-to-hast: ^13.2.0
  minimist: ^1.2.8
  monaco-editor-core: ^0.52.2
  ofetch: ^1.4.1
  ohash: ^2.0.9
  oniguruma-to-es: ^3.1.1
  pinia: ^3.0.1
  pnpm: ^10.5.2
  prettier: ^3.5.2
  rehype-raw: ^7.0.0
  rehype-stringify: ^10.0.1
  remark-parse: ^11.0.0
  remark-rehype: ^11.1.1
  rimraf: ^6.0.1
  rollup: ^4.34.9
  rollup-plugin-copy: ^3.5.0
  rollup-plugin-dts: ^6.1.1
  rollup-plugin-esbuild: ^6.2.1
  simple-git-hooks: ^2.11.1
  taze: ^18.6.0
  tm-grammars: ^1.22.19
  tm-themes: ^1.9.14
  twoslash: ^0.3.1
  twoslash-vue: ^0.3.1
  typescript: ^5.8.2
  unbuild: ^3.5.0
  unified: ^11.0.5
  unist-util-visit: ^5.0.0
  unocss: ^66.0.0
  unplugin-vue-components: ^28.4.1
  vite: ^6.2.0
  vite-tsconfig-paths: ^5.1.4
  vitepress: ^2.0.0-alpha.3
  vitepress-plugin-group-icons: ^1.3.6
  vitepress-plugin-mermaid: ^2.0.17
  vitest: ^3.0.7
  vitest-package-exports: ^0.1.0
  vscode-oniguruma: 1.7.0
  vue: ^3.5.13
  vue-tsc: ^2.2.8
  wrangler: ^3.111.0
