packages:
  - packages/*
  - packages/*/playground
  - playground
  - examples/*
  - docs
  - packages/@shikijs/core/vendor/*
catalog:
  '@antfu/eslint-config': ^3.14.0
  '@antfu/ni': ^23.2.0
  '@antfu/utils': ^8.1.0
  '@iconify-json/carbon': ^1.2.5
  '@iconify-json/codicon': ^1.2.8
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/svg-spinners': ^1.2.2
  '@rollup/plugin-alias': ^5.1.1
  '@rollup/plugin-commonjs': ^28.0.2
  '@rollup/plugin-json': ^6.1.0
  '@rollup/plugin-node-resolve': ^16.0.0
  '@rollup/plugin-replace': ^6.0.2
  '@rollup/plugin-terser': ^0.4.4
  '@shikijs/vscode-textmate': ^10.0.1
  '@types/fs-extra': ^11.0.4
  '@types/hast': ^3.0.4
  '@types/markdown-it': ^14.1.2
  '@types/mdast': ^4.0.4
  '@types/minimist': ^1.2.5
  '@types/node': ^22.10.7
  '@types/unist': ^3.0.3
  '@unocss/reset': ^65.4.2
  '@vitest/coverage-v8': ^3.0.2
  '@vueuse/core': ^12.4.0
  ansi-sequence-parser: ^1.1.1
  bumpp: ^9.10.1
  cac: ^6.7.14
  chalk: ^5.4.1
  diff-match-patch-es: ^1.0.1
  eslint: ^9.18.0
  eslint-plugin-format: ^1.0.1
  esno: ^4.8.0
  fast-glob: ^3.3.3
  floating-vue: ^5.2.2
  fs-extra: ^11.3.0
  fuse.js: ^7.0.0
  hast-util-from-html: ^2.0.3
  hast-util-to-html: ^9.0.4
  hast-util-to-string: ^3.0.1
  jiti: ^2.4.2
  jsonc-parser: ^3.3.1
  lint-staged: ^15.4.1
  markdown-it: ^14.1.0
  mdast-util-from-markdown: ^2.0.2
  mdast-util-gfm: ^3.0.0
  mdast-util-to-hast: ^13.2.0
  minimist: ^1.2.8
  monaco-editor-core: ^0.52.2
  ofetch: ^1.4.1
  ohash: ^1.1.4
  oniguruma-to-es: ^2.2.0
  picocolors: ^1.1.1
  pinia: ^2.3.0
  pnpm: ^9.15.4
  prettier: ^3.4.2
  rehype-raw: ^7.0.0
  rehype-stringify: ^10.0.1
  remark-parse: ^11.0.0
  remark-rehype: ^11.1.1
  rimraf: ^6.0.1
  rollup: ^4.31.0
  rollup-plugin-copy: ^3.5.0
  rollup-plugin-dts: ^6.1.1
  rollup-plugin-esbuild: ^6.1.1
  shiki-legacy: npm:shiki@^0.14.7
  simple-git-hooks: ^2.11.1
  taze: ^18.2.0
  tm-grammars: ^1.22.8
  tm-themes: ^1.9.8
  twoslash: ^0.2.12
  twoslash-vue: ^0.2.12
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unified: ^11.0.5
  unist-util-visit: ^5.0.0
  unocss: ^65.4.2
  unplugin-vue-components: ^28.0.0
  vite: ^6.0.7
  vite-tsconfig-paths: ^5.1.4
  vitepress: ^1.5.0
  vitepress-plugin-mermaid: ^2.0.17
  vitest: ^3.0.2
  vscode-oniguruma: 1.7.0
  vue: ^3.5.13
  vue-tsc: ^2.2.0
  wrangler: ^3.103.2
