import fs from 'fs-extra'
import { themes as allThemes } from 'tm-themes'

export async function prepareTheme(): Promise<void> {
  const themes = await Promise.all(allThemes
    .map(async (t) => {
      const theme = await fs.readJSON(`./node_modules/tm-themes/themes/${t.name}.json`)

      await fs.writeFile(
        `./dist/${t.name}.mjs`,
        `/* Theme: ${theme.name} */
export default Object.freeze(JSON.parse(${JSON.stringify(JSON.stringify(theme))}))
`,
        'utf-8',
      )

      await fs.writeFile(
        `./dist/${t.name}.d.mts`,
        `import type { ThemeRegistration } from '@shikijs/core'
const theme: ThemeRegistration
export default theme
`,
        'utf-8',
      )

      return {
        id: t.name,
        displayName: theme.displayName,
        type: theme.type,
        import: `__(() => import('@shikijs/themes/${t.name}')) as unknown as DynamicImportThemeRegistration__`,
      }
    }))

  await fs.writeFile(
    'dist/index.mjs',
    `export const themeNames = [
${themes.map(i => `  '${i.id}',`).join('\n')}
]
`,
    'utf-8',
  )

  await fs.writeFile(
    'dist/index.d.mts',
    `export const themeNames: readonly string[]
`,
    'utf-8',
  )

  const packageJson = JSON.parse(await fs.readFile('./package.json', 'utf-8'))
  packageJson.exports = {
    '.': './dist/index.mjs',
    ...Object.fromEntries(
      themes.map(i => [
        `./${i.id}`,
        `./dist/${i.id}.mjs`,
      ]),
    ),
  }
  await fs.writeFile('./package.json', `${JSON.stringify(packageJson, null, 2)}\n`, 'utf-8')

  await fs.writeFile(
    '../shiki/src/themes.ts',
    `// Generated by packages/themes/scripts/prepare.ts
import type { DynamicImportThemeRegistration, BundledThemeInfo } from '@shikijs/core'

export const bundledThemesInfo: BundledThemeInfo[] = ${JSON.stringify(themes, null, 2).replace(/"__|__"/g, '')}

export type BundledTheme =
${themes.map(i => `  | '${i.id}'`).join('\n')}

export const bundledThemes = Object.fromEntries(bundledThemesInfo.map(i => [i.id, i.import])) as Record<BundledTheme, DynamicImportThemeRegistration>
`,
    'utf-8',
  )
}
