/**
 * Generated by scripts/prepare.ts
 */
import type { DynamicImportLanguageRegistration, BundledLanguageInfo } from 'shikiji-core'

export const bundledLanguagesInfo: BundledLanguageInfo[] = [
  {
    'id': 'astro',
    'name': 'Astro',
    'import': (() => import('./langs/astro')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'blade',
    'name': 'Blade',
    'import': (() => import('./langs/blade')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'c',
    'name': 'C',
    'import': (() => import('./langs/c')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'coffee',
    'name': 'CoffeeScript',
    'aliases': [
      'coffeescript'
    ],
    'import': (() => import('./langs/coffee')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'cpp',
    'name': 'C++',
    'aliases': [
      'c++'
    ],
    'import': (() => import('./langs/cpp')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'css',
    'name': 'CSS',
    'import': (() => import('./langs/css')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'glsl',
    'name': 'GLSL',
    'import': (() => import('./langs/glsl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'graphql',
    'name': 'GraphQL',
    'aliases': [
      'gql'
    ],
    'import': (() => import('./langs/graphql')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'haml',
    'name': 'Ruby Haml',
    'import': (() => import('./langs/haml')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'handlebars',
    'name': 'Handlebars',
    'aliases': [
      'hbs'
    ],
    'import': (() => import('./langs/handlebars')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'html',
    'name': 'HTML',
    'import': (() => import('./langs/html')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'http',
    'name': 'HTTP',
    'import': (() => import('./langs/http')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'imba',
    'name': 'Imba',
    'import': (() => import('./langs/imba')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'java',
    'name': 'Java',
    'import': (() => import('./langs/java')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'javascript',
    'name': 'JavaScript',
    'aliases': [
      'js'
    ],
    'import': (() => import('./langs/javascript')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'jinja',
    'name': 'Jinja',
    'import': (() => import('./langs/jinja')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'jison',
    'name': 'Jison',
    'import': (() => import('./langs/jison')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'json',
    'name': 'JSON',
    'import': (() => import('./langs/json')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'json5',
    'name': 'JSON5',
    'import': (() => import('./langs/json5')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'jsonc',
    'name': 'JSON with Comments',
    'import': (() => import('./langs/jsonc')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'jsonl',
    'name': 'JSON Lines',
    'import': (() => import('./langs/jsonl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'jsx',
    'name': 'JSX',
    'import': (() => import('./langs/jsx')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'julia',
    'name': 'Julia',
    'import': (() => import('./langs/julia')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'less',
    'name': 'Less',
    'import': (() => import('./langs/less')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'lua',
    'name': 'Lua',
    'import': (() => import('./langs/lua')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'markdown',
    'name': 'Markdown',
    'aliases': [
      'md'
    ],
    'import': (() => import('./langs/markdown')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'marko',
    'name': 'Marko',
    'import': (() => import('./langs/marko')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'mdc',
    'name': 'mdc',
    'import': (() => import('./langs/mdc')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'mdx',
    'name': 'MDX',
    'import': (() => import('./langs/mdx')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'php',
    'name': 'PHP',
    'import': (() => import('./langs/php')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'postcss',
    'name': 'PostCSS',
    'import': (() => import('./langs/postcss')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'pug',
    'name': 'Pug',
    'aliases': [
      'jade'
    ],
    'import': (() => import('./langs/pug')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'python',
    'name': 'Python',
    'aliases': [
      'py'
    ],
    'import': (() => import('./langs/python')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'r',
    'name': 'R',
    'import': (() => import('./langs/r')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'ruby',
    'name': 'Ruby',
    'aliases': [
      'rb'
    ],
    'import': (() => import('./langs/ruby')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'sass',
    'name': 'Sass',
    'import': (() => import('./langs/sass')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'scss',
    'name': 'SCSS',
    'import': (() => import('./langs/scss')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'shellscript',
    'name': 'Shell',
    'aliases': [
      'bash',
      'sh',
      'shell',
      'zsh'
    ],
    'import': (() => import('./langs/shellscript')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'sql',
    'name': 'SQL',
    'import': (() => import('./langs/sql')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'stylus',
    'name': 'Stylus',
    'aliases': [
      'styl'
    ],
    'import': (() => import('./langs/stylus')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'svelte',
    'name': 'Svelte',
    'import': (() => import('./langs/svelte')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'toml',
    'name': 'TOML',
    'import': (() => import('./langs/toml')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'tsx',
    'name': 'TSX',
    'import': (() => import('./langs/tsx')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'typescript',
    'name': 'TypeScript',
    'aliases': [
      'ts'
    ],
    'import': (() => import('./langs/typescript')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'vue',
    'name': 'Vue',
    'import': (() => import('./langs/vue')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'vue-html',
    'name': 'Vue HTML',
    'import': (() => import('./langs/vue-html')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'wasm',
    'name': 'WebAssembly',
    'import': (() => import('./langs/wasm')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'wgsl',
    'name': 'WGSL',
    'import': (() => import('./langs/wgsl')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'xml',
    'name': 'XML',
    'import': (() => import('./langs/xml')) as DynamicImportLanguageRegistration
  },
  {
    'id': 'yaml',
    'name': 'YAML',
    'aliases': [
      'yml'
    ],
    'import': (() => import('./langs/yaml')) as DynamicImportLanguageRegistration
  }
]

export const bundledLanguagesBase = Object.fromEntries(bundledLanguagesInfo.map(i => [i.id, i.import]))

export const bundledLanguagesAlias = Object.fromEntries(bundledLanguagesInfo.flatMap(i => i.aliases?.map(a => [a, i.import]) || []))

export type BundledLanguage = 'astro' | 'bash' | 'blade' | 'c' | 'c++' | 'coffee' | 'coffeescript' | 'cpp' | 'css' | 'glsl' | 'gql' | 'graphql' | 'haml' | 'handlebars' | 'hbs' | 'html' | 'http' | 'imba' | 'jade' | 'java' | 'javascript' | 'jinja' | 'jison' | 'js' | 'json' | 'json5' | 'jsonc' | 'jsonl' | 'jsx' | 'julia' | 'less' | 'lua' | 'markdown' | 'marko' | 'md' | 'mdc' | 'mdx' | 'php' | 'postcss' | 'pug' | 'py' | 'python' | 'r' | 'rb' | 'ruby' | 'sass' | 'scss' | 'sh' | 'shell' | 'shellscript' | 'sql' | 'styl' | 'stylus' | 'svelte' | 'toml' | 'ts' | 'tsx' | 'typescript' | 'vue' | 'vue-html' | 'wasm' | 'wgsl' | 'xml' | 'yaml' | 'yml' | 'zsh'

export const bundledLanguages = {
  ...bundledLanguagesBase,
  ...bundledLanguagesAlias,
} as Record<BundledLanguage, DynamicImportLanguageRegistration>
