/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badges: typeof import('./.vitepress/components/Badges.vue')['default']
    copy: typeof import('./.vitepress/components/LanguagesList copy.vue')['default']
    FunctionsList: typeof import('./.vitepress/components/FunctionsList.vue')['default']
    GrammarList: typeof import('./.vitepress/components/GrammarList.vue')['default']
    HomeDemo: typeof import('./.vitepress/components/HomeDemo.vue')['default']
    LanguagesList: typeof import('./.vitepress/components/LanguagesList.vue')['default']
    LanugagesList: typeof import('./.vitepress/components/LanugagesList.vue')['default']
    ShikijiMiniPlayground: typeof import('./.vitepress/components/ShikijiMiniPlayground.vue')['default']
    ShikijiPlayground: typeof import('./.vitepress/components/ShikijiPlayground.vue')['default']
    ThemesList: typeof import('./.vitepress/components/ThemesList.vue')['default']
  }
}
