/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badges: typeof import('./.vitepress/components/Badges.vue')['default']
    FundingButton: typeof import('./.vitepress/components/FundingButton.vue')['default']
    HomeDemo: typeof import('./.vitepress/components/HomeDemo.vue')['default']
    LanguagesList: typeof import('./.vitepress/components/LanguagesList.vue')['default']
    ShikiMiniPlayground: typeof import('./.vitepress/components/ShikiMiniPlayground.vue')['default']
    ShikiPlayground: typeof import('./.vitepress/components/ShikiPlayground.vue')['default']
    ThemesList: typeof import('./.vitepress/components/ThemesList.vue')['default']
  }
}
